
auth.token=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

defaults.org=service-confoinnoinc
defaults.project=react-native

defaults.url=https://sentry.io/
