services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backrelief_api
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./backend/:/api
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: backrelief
      POSTGRES_PASSWORD: password100
      POSTGRES_DB: healthtracker
      PGDATA: customDataFolder
    ports:
      - "5433:5432"
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d healthtracker -U backrelief" ]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
      build:
        context: ./front-client
        dockerfile: Dockerfile
      ports:
        - "8081:8081"     # Metro bundler (React Native dev)
        - "19000:19000"   # Expo
        - "19001:19001"   # Expo
        - "19002:19002"   # Expo Web
      volumes:
        - ./front-client:/app
      stdin_open: true
      tty: true
  #    depends_on:
  #      - api