export const painLocations =  [
      "Abdos",
      "Avant-bras",
      "Biceps",
      "Carpe",
      "deltoid droit",
      "Fessier gauche",
      "Fessier-Droit",
      "Grand dorsal gauche",
      "Grand Rond droit",
      "Grand Rond gauche",
      "Grand-dorsal-droit",
      "Tête",
      "Ischio-jambier",
      "Long extenseur",
      "Main",
      "Mollet droit",
      "Mollet gauche",
      "Oblique",
      "Pied droit",
      "Pied gauche",
      "Quadriceps",
      "Tibiat droit-1",
      "Tibiat droit",
      "Tibiat gauche-1",
      "Tibiat gauche",
      "Trapèze",
      "Triceps",
      "Abdos Lateral",
      "Tibiat Anterieur Droit",
      "Intercostaux",
      "Tibiat Anterieur Gauche",
      "Main Droite",
      "Main Gauche",
      "Avant-Bras-Droit",
      "Triceps-Droit",
      "Supinateur-Droit",
      "Supinateur-Gauche",
      "Triceps-Gauche",
      "Biceps-Gauche",
      "Tibiat-Gauche-Lateral",
      "Fessier-Gauche-Lateral",
      "Pied-Droit-Anterieur",
      "Pied-Gauche-Anterieur",
      "Tronc"
];