export const painLocations =  [
      "Abdos",
      "Avant-bras",
      "Biceps",
      "Carpe",
      "Deltoid Droit",
      "Fessier gauche",
      "Fessier-Droit",
      "Grand dorsal gauche",
      "Grand Rond droit",
      "Grand Rond gauche",
      "Grand-dorsal-droit",
      "Tête",
      "Ischio-jambier",
      "Long extenseur",
      "Main",
      "Mollet droit",
      "Mollet gauche",
      "Oblique",
      "Pied droit",
      "Pied gauche",
      "Quadriceps",
      "Tibiat droit-1",
      "Tibiat droit",
      "Tibiat gauche-1",
      "Tibiat gauche",
      "Trapèze",
      "Triceps",
      "Abdos Lateral",
      "Tibiat Anterieur Droit",
      "Intercostaux",
      "Tibiat Anterieur Gauche",
      "Main Droite",
      "Main Gauche",
      "Avant Bras Droit",
      "Avant Bras Gauche",
      "Triceps-Droit",
      "Supinateur Droit",
      "Supinateur Gauche",
      "Triceps Gauche",
      "Biceps Gauche",
      "Tibiat Gauche Lateral",
      "Tibiat Gauche Lateral 1",
      "Fessier Gauche Lateral",
      "Pied Droit Anterieur",
      "Pied Gauche Anterieur",
      "Tronc",
      "Biceps Droit",
      "Pectoral Gauche",
      "Pectoral Droit",
      "Tête Face",
      "Deltoid Gauche Lateral",
      "Deltoid Droit Lateral",
      "Quadriceps Droit",
      "Quadriceps-Gauche",
      "Bicesps Femoral Droit",
      "Bicesps Femoral Gauche"
];