name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    env:
      MODE: DEV 

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DATABASE }}
          PGDATA: customDataFolder
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Create .env file
      run: |
        echo "MODE=DEV" >> backend/.env
        echo "POSTGRES_HOST=localhost" >> backend/.env
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> backend/.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> backend/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> backend/.env
        echo "POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}" >> backend/.env

    - name: Run backend tests
      working-directory: ./backend
      run: npm run test

    - name: Healthcheck backend
      working-directory: ./backend
      run: |
        npm run start:dev &
        sleep 10
        curl --fail http://localhost:3000/health || exit 1

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install frontend dependencies
      working-directory: ./front-client
      run: npm ci

    - name: Lint frontend code
      working-directory: ./front-client
      run: npm run lint

    - name: Run frontend tests
      working-directory: ./front-client
      run: npm test